export const INJECTION_TOKENS = {
  REST_CONFIG: 'REST_CONFIG',
  GRAPHQL_CONFIG: 'GRAPHQL_CONFIG',
  WS_CONFIG: 'WS_CONFIG',
  GRPC_CONFIG: 'GRPC_CONFIG',
  WEBHOOK_CONFIG: 'WEBHOOK_CONFIG',
  SSE_CONFIG: 'SSE_CONFIG',
} as const; 